gems:
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - config.rb
  - bower.json

defaults:
  - scope:
      path: "/"
      type: pages
    values:
      layouts: default
  - scope:
      path: "documentation"
      type: pages
    values:
      layout: doc-page
      priority: 0.8

markdown: kramdown

kramdown:
  input: kramdown
  hard_wrap: false

sass:
  sass_dir: bower_components/foundation/scss
